python main.py --name GCN --dataset avazu-ctr --split RL --transductive True --model GCN --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp False --compile False --device cuda:0
python main.py --name GCN_CLATT --dataset avazu-ctr --split RL --transductive True --model GCN-CLATT --clusterings la --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp False --compile True --device cuda:0

python main.py --name GraphSAGE --dataset avazu-ctr --split RL --transductive True --model GraphSAGE --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile False --device cuda:0
python main.py --name GraphSAGE_CLATT --dataset avazu-ctr --split RL --transductive True --model GraphSAGE-CLATT --clusterings la --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp False --compile True --device cuda:0

python main.py --name LGT --dataset avazu-ctr --split RL --transductive True --model GT --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile False --device cuda:0
python main.py --name LGT_CLATT --dataset avazu-ctr --split RL --transductive True --model GT-CLATT --clusterings la --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0

python main.py --name GGT_DW --dataset avazu-ctr --split RL --transductive True --model GGT --node_embeddings embs_dw --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0
python main.py --name GGT_DW_CLATT --dataset avazu-ctr --split RL --transductive True --model GGT-CLATT --node_embeddings embs_dw  --clusterings la --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0

python main.py --name GGT_Lap --dataset avazu-ctr --split RL --transductive True --model GGT --node_embeddings embs_lap --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0
python main.py --name GGT_Lap_CLATT --dataset avazu-ctr --split RL --transductive True --model GGT-CLATT --node_embeddings embs_lap  --clusterings la --regression_targets_transform standard-scaler none --numerical_features_transform quantile-transform-normal --fraction_features_transform quantile-transform-normal quantile-transform-uniform --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0
