python main.py --name GCN --dataset tolokers-2 --split RL --transductive True --model GCN --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile False --device cuda:0
python main.py --name GCN_CLATT --dataset tolokers-2 --split RL --transductive True --model GCN-CLATT --clusterings bpp --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0

python main.py --name GraphSAGE --dataset tolokers-2 --split RL --transductive True --model GraphSAGE --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile False --device cuda:0
python main.py --name GraphSAGE_CLATT --dataset tolokers-2 --split RL --transductive True --model GraphSAGE-CLATT --clusterings bpp --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0

python main.py --name LGT --dataset tolokers-2 --split RL --transductive True --model GT --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile False --device cuda:0
python main.py --name LGT_CLATT --dataset tolokers-2 --split RL --transductive True --model GT-CLATT --clusterings bpp --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0

python main.py --name GGT_DW --dataset tolokers-2 --split RL --transductive True --model GGT --node_embeddings embs_dw --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0
python main.py --name GGT_DW_CLATT --dataset tolokers-2 --split RL --transductive True --model GGT-CLATT --node_embeddings embs_dw  --clusterings bpp --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0

python main.py --name GGT_Lap --dataset tolokers-2 --split RL --transductive True --model GGT --node_embeddings embs_lap --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0
python main.py --name GGT_Lap_CLATT --dataset tolokers-2 --split RL --transductive True --model GGT-CLATT --node_embeddings embs_lap  --clusterings bpp --regression_targets_transform none --numerical_features_transform quantile-transform-normal standard-scaler --fraction_features_transform none --lr 3e-05 1e-04 3e-04 1e-03 3e-03 --dropout 0 0.1 0.2 --amp True --compile True --device cuda:0
